# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  GitHubUsername: NF-Software-Inc

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: |
          9.0.x
          8.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./easy-blazor-bulma
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./easy-blazor-bulma
