# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish-mac-catalyst
on:
  workflow_call:
    inputs:
      build:
        required: true
        type: string
      version:
        required: true
        type: string

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  GitHubUsername: NF-Software-Inc
  PublishVersion: ${{ inputs.version }}.${{ inputs.build }}
  TempDirectory: ${{ github.workspace }}/Temp-Mac-Catalyst

jobs:
  publish:
    name: Publish Easy Blazor Bulma Mac Catalyst
    runs-on: macos-15
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: |
          9.0.x
          8.0.x
          6.0.x
    - name: Install MAUI
      run: |
        sw_vers -productVersion
        ls /Applications | grep 'Xcode'
        dotnet workload install ios maui-android maui-maccatalyst --version 9.0.101
        dotnet workload list
      working-directory: ./easy-blazor-bulma-demo
    - run: mkdir ${{ env.TempDirectory }}
    - name: Publish
      run: dotnet publish -c Release -f net9.0-maccatalyst -p:MtouchLink=SdkOnly -p:CreatePackage=true -p:UseHardenedRuntime=true -p:AssemblyVersion=${{ env.PublishVersion }} -p:Version=${{ inputs.version }} -p:FileVersion=${{ env.PublishVersion }} -p:ApplicationVersion=${{ inputs.build }} -p:ApplicationDisplayVersion=${{ inputs.version }}
      working-directory: ./easy-blazor-bulma-demo
    - name: Add to Release
      run: gh release upload ${{ inputs.version }} ${{ github.workspace }}/easy-blazor-bulma-demo/bin/Release/net9.0-maccatalyst/publish/Easy-Blazor-Bulma-Demo.pkg
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: easy-blazor-bulma-demo-maccatalyst
        if-no-files-found: error
        retention-days: 7
        path: ${{ github.workspace }}/easy-blazor-bulma-demo/bin/Release/net9.0-maccatalyst/publish/*.pkg
