# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
    workflow_dispatch:
      inputs:
        targets:
          description: Targets
          required: true
          type: string
        version:
          description: Version
          required: true
          type: string
        build:
          description: Build
          required: true
          type: string
    release:
      types: [ published ]

env:
  Targets: ${{ github.event.release.name }}
  Version: ${{ github.event.release.tag_name }}
  Build: ${{ github.run_number }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Update Environment Variables
        run: |
          echo "Targets=${{ github.event.inputs.targets }}" >> $GITHUB_ENV
          echo "Version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "Build=${{ github.event.inputs.build }}" >> $GITHUB_ENV
  android:
    needs: [ prepare ]
    if: contains(env.Targets, 'All') || contains(env.Targets, 'MAUI') || contains(env.Targets, 'Android')
    uses: ./.github/workflows/publish-android.yml
    with:
      build: ${{ env.Build }}
      version: ${{ env.Version }}
    secrets: inherit
  ios:
    needs: [ prepare ]
    if: contains(env.Targets, 'All') || contains(env.Targets, 'MAUI') || contains(env.Targets, 'iOS')
    uses: ./.github/workflows/publish-ios.yml
    with:
      build: ${{ env.Build }}
      version: ${{ env.Version }}
    secrets: inherit
  nuget:
    needs: [ prepare ]
    if: contains(env.Targets, 'All') || contains(env.Targets, 'NuGet')
    uses: ./.github/workflows/publish-nuget.yml
    with:
      build: ${{ env.Build }}
      version: ${{ env.Version }}
    secrets: inherit
  mac-catalyst:
    needs: [ prepare ]
    if: contains(env.Targets, 'All') || contains(env.Targets, 'MAUI') || contains(env.Targets, 'Mac Catalyst')
    uses: ./.github/workflows/publish-mac-catalyst.yml
    with:
      build: ${{ env.Build }}
      version: ${{ env.Version }}
    secrets: inherit
  windows-arm64:
    needs: [ prepare ]
    if: contains(env.Targets, 'All') || contains(env.Targets, 'MAUI') || contains(env.Targets, 'Windows')
    uses: ./.github/workflows/publish-windows.yml
    with:
      architecture: arm64
      build: ${{ env.Build }}
      version: ${{ env.Version }}
    secrets: inherit
  windows-x64:
    needs: [ prepare ]
    if: contains(env.Targets, 'All') || contains(env.Targets, 'MAUI') || contains(env.Targets, 'Windows')
    uses: ./.github/workflows/publish-windows.yml
    with:
      architecture: x64
      build: ${{ env.Build }}
      version: ${{ env.Version }}
    secrets: inherit
