# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
    workflow_dispatch:
    release:
      types: [ published ]

jobs:
  android:
    if: ${{ contains(github.event.release.name, 'All') || contains(github.event.release.name, 'MAUI') || contains(github.event.release.name, 'Android') }}
    uses: ./.github/workflows/publish-android.yml
    secrets: inherit
  ios:
    if: ${{ contains(github.event.release.name, 'All') || contains(github.event.release.name, 'MAUI') || contains(github.event.release.name, 'iOS') }}
    uses: ./.github/workflows/publish-ios.yml
    secrets: inherit
  nuget:
    if: ${{ contains(github.event.release.name, 'All') || contains(github.event.release.name, 'NuGet') }}
    uses: ./.github/workflows/publish-nuget.yml
    secrets: inherit
  mac-catalyst:
    if: ${{ contains(github.event.release.name, 'All') || contains(github.event.release.name, 'MAUI') || contains(github.event.release.name, 'Mac Catalyst') }}
    uses: ./.github/workflows/publish-mac-catalyst.yml
    secrets: inherit
  windows-arm64:
    if: ${{ contains(github.event.release.name, 'All') || contains(github.event.release.name, 'MAUI') || contains(github.event.release.name, 'Windows') }}
    uses: ./.github/workflows/publish-windows.yml
    with:
      architecture: arm64
    secrets: inherit
  windows-x64:
    if: ${{ contains(github.event.release.name, 'All') || contains(github.event.release.name, 'MAUI') || contains(github.event.release.name, 'Windows') }}
    uses: ./.github/workflows/publish-windows.yml
    with:
      architecture: x64
    secrets: inherit
