# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish-android
on:
  workflow_call:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  GitHubUsername: NF-Software-Inc
  PublishVersion: ${{ github.event.release.tag_name }}.${{ github.run_number }}
  TempDirectory: ${{ github.workspace }}\Temp

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
          6.0.x
    - name: Install MAUI
      run: dotnet workload install maui-android
      working-directory: .\easy-blazor-bulma-demo
    - name: Get KeyStore
      run: |
        New-Item -Type Directory -Path ${{ env.TempDirectory }}
        $keystore = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String(${{ secrets.ANDROID_KEYSTORE_OPENSOURCE }}))
        New-Item -Type File -Path ${{ env.TempDirectory }}\opensource.keystore -Value $keystore
    - name: Build & Publish
      run: |
        dotnet build -c Release -f net9.0-android
        dotnet publish -c Release -f net9.0-android -p:AndroidKeyStore=true -p:AndroidSigningKeyStore='${{ env.TempDirectory }}\opensource.keystore' -p:AndroidSigningKeyAlias='${{ secrets.ANDROID_ALIAS_OPENSOURCE }}' -p:AndroidSigningKeyPass='${{ secrets.ANDROID_PASSWORD_OPENSOURCE }}' -p:AndroidSigningStorePass='${{ secrets.ANDROID_PASSWORD_OPENSOURCE }}'
      working-directory: .\easy-blazor-bulma-demo
    - name: Zip & Upload
      run: |
        Get-ChildItem "${{ github.workspace }}\easy-blazor-bulma-demo\bin\Release\net8.0-android\*Signed.apk", "${{ github.workspace }}\easy-blazor-bulma-demo\bin\Release\net8.0-android\*.aab" | Compress-Archive -DestinationPath ${{ env.TempDirectory }}\easy-blazor-bulma-demo-android.zip
        gh release upload ${{ github.event.release.tag_name }} ${{ env.TempDirectory }}\easy-blazor-bulma-demo-android.zip
