# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish-ios
on:
  workflow_call:
    inputs:
      build:
        required: true
        type: string
      version:
        required: true
        type: string

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  GitHubUsername: NF-Software-Inc
  PublishVersion: ${{ inputs.version }}.${{ inputs.build }}
  TempDirectory: ${{ github.workspace }}/Temp-iOS

jobs:
  publish:
    name: Publish Easy Blazor Bulma iOS
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: |
          9.0.x
          8.0.x
          6.0.x
    - name: Install MAUI
      run: dotnet workload install maui-android maui-ios
      working-directory: ./easy-blazor-bulma-demo
    - run: mkdir ${{ env.TempDirectory }}
    - name: Publish
      run: dotnet publish -c Release -f net9.0-ios -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:EnableAssemblyILStripping=false -p:AssemblyVersion=${{ env.PublishVersion }} -p:Version=${{ inputs.version }} -p:FileVersion=${{ env.PublishVersion }} -p:ApplicationVersion=${{ inputs.build }} -p:ApplicationDisplayVersion=${{ inputs.version }}
      working-directory: ./easy-blazor-bulma-demo
    - name: Add to Release
      run: gh release upload ${{ inputs.version }} ${{ github.workspace }}/easy-blazor-bulma-demo/bin/Release/net9.0-ios/ios-arm64/publish/Easy-Blazor-Bulma-Demo.ipa
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: easy-blazor-bulma-demo-ios
        if-no-files-found: error
        retention-days: 7
        path: ${{ github.workspace }}/easy-blazor-bulma-demo/bin/Release/net9.0-ios/ios-arm64/publish/*.ipa
