# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
    workflow_dispatch:
      inputs:
        targets:
          description: Targets
          required: true
          type: string
        version:
          description: Version
          required: true
          type: string
        build:
          description: Build
          type: string
    release:
      types: [ published ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Update Environment Variables
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            echo "Targets=${{ github.event.inputs.targets }}" >> $GITHUB_OUTPUT
            echo "Version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "Build=${{ github.event.inputs.build || github.run_number }}" >> $GITHUB_OUTPUT
          else
            echo "Targets=${{ github.event.release.name }}" >> $GITHUB_OUTPUT
            echo "Version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            echo "Build=${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
  android:
    needs: [ prepare ]
    if: ${{ contains(needs.prepare.outputs.Targets, 'All') || contains(needs.prepare.outputs.Targets, 'MAUI') || contains(needs.prepare.outputs.Targets, 'Android') }}
    uses: ./.github/workflows/publish-android.yml
    with:
      build: ${{ needs.prepare.outputs.Build }}
      version: ${{ needs.prepare.outputs.Version }}
    secrets: inherit
  ios:
    needs: [ prepare ]
    if: ${{ contains(needs.prepare.outputs.Targets, 'All') || contains(needs.prepare.outputs.Targets, 'MAUI') || contains(needs.prepare.outputs.Targets, 'iOS') }}
    uses: ./.github/workflows/publish-ios.yml
    with:
      build: ${{ needs.prepare.outputs.Build }}
      version: ${{ needs.prepare.outputs.Version }}
    secrets: inherit
  nuget:
    needs: [ prepare ]
    if: ${{ contains(needs.prepare.outputs.Targets, 'All') || contains(needs.prepare.outputs.Targets, 'NuGet') }}
    uses: ./.github/workflows/publish-nuget.yml
    with:
      build: ${{ needs.prepare.outputs.Build }}
      version: ${{ needs.prepare.outputs.Version }}
    secrets: inherit
  mac-catalyst:
    needs: [ prepare ]
    if: ${{ contains(needs.prepare.outputs.Targets, 'All') || contains(needs.prepare.outputs.Targets, 'MAUI') || contains(needs.prepare.outputs.Targets, 'Mac Catalyst') }}
    uses: ./.github/workflows/publish-mac-catalyst.yml
    with:
      build: ${{ needs.prepare.outputs.Build }}
      version: ${{ needs.prepare.outputs.Version }}
    secrets: inherit
  windows-arm64:
    needs: [ prepare ]
    if: ${{ contains(needs.prepare.outputs.Targets, 'All') || contains(needs.prepare.outputs.Targets, 'MAUI') || contains(needs.prepare.outputs.Targets, 'Windows') }}
    uses: ./.github/workflows/publish-windows.yml
    with:
      architecture: arm64
      build: ${{ needs.prepare.outputs.Build }}
      version: ${{ needs.prepare.outputs.Version }}
    secrets: inherit
  windows-x64:
    needs: [ prepare ]
    if: ${{ contains(needs.prepare.outputs.Targets, 'All') || contains(needs.prepare.outputs.Targets, 'MAUI') || contains(needs.prepare.outputs.Targets, 'Windows') }}
    uses: ./.github/workflows/publish-windows.yml
    with:
      architecture: x64
      build: ${{ needs.prepare.outputs.Build }}
      version: ${{ needs.prepare.outputs.Version }}
    secrets: inherit
